### PR TITLE
Fix VapourSynth error handling and other issues

### PR DESCRIPTION
**Pull request by myrsloik**
You must set an error when returning NULL. And never return a frame after setting an error.

Added header update and set proper flags for the filters.

### CODE REVIEW

**Comment by VFR-maniac** [comment]
Hmmm...
I apply your patches but I notice that I get jerkiness when I preview video frames on VirtualDub. Myrsloik, it seems nfMakeLinear makes duplicated calling of frame getter within consecutive frame requests. This request behavior brings about unnecessary decodings from random access points since requested frame numbers are back and forth. L-SMASH Works plugins does not assume such behavior. I'll revert this change unless you have a solution.

**Comment by myrsloik** [comment]
I'll test it and see if it's a bug

**Comment by myrsloik** [comment]
Exactly what script do you use for testing? Just a single source and nothing else?

**Comment by VFR-maniac** [comment]
Yes.

```
import vapoursynth as vs
core = vs.get_core()
core.std.LoadPlugin(path=r'vslsmashsource.dll')
filename = r'source.mp4'
clip = core.lsmas.LibavSMASHSource(filename, dr=0, variable=0)
clip.set_output()
```

**Comment by VFR-maniac** [comment]
The bellow is what gdb shows on linear access from 1st to 2nd frame.

```
Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=1)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.
[Thread 6872.0x2278 exited with code 0]
[Thread 6872.0x368 exited with code 0]
[Thread 6872.0x1a00 exited with code 0]
[Thread 6872.0x2768 exited with code 0]
[Thread 6872.0xedc exited with code 0]
[New Thread 6872.0x1c7c]
[New Thread 6872.0x1924]
[New Thread 6872.0x2234]
[New Thread 6872.0x754]
[New Thread 6872.0x30c]

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=2)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=3)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=4)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=2)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.
[Thread 6872.0x1c7c exited with code 0]
[Thread 6872.0x1924 exited with code 0]
[Thread 6872.0x2234 exited with code 0]
[Thread 6872.0x754 exited with code 0]
[Thread 6872.0x30c exited with code 0]
[New Thread 6872.0xad8]
[New Thread 6872.0x239c]
[New Thread 6872.0x71c]
[New Thread 6872.0x2378]
[New Thread 6872.0x26ec]

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=3)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.
[New Thread 6872.0xc50]

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=4)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb) c
Continuing.

Breakpoint 1, libavsmash_video_get_frame (vdhp=0x2c22fd0, vohp=0x2c233b0, sample_number=5)
    at ../common/libavsmash_video.c:1010
1010        if( vohp->vfr2cfr )
(gdb)
```

**Comment by myrsloik** [comment]
So this apparently only happens in vdub and not vspipe. Or at least is manymanymany times less likely to happen there. Well spotted. Now to figure out why...

**Comment by myrsloik** [comment]
What's your cpu? I think it could depend on how many threads are used.

**Comment by myrsloik** [comment]
https://dl.dropboxusercontent.com/u/73468194/vapoursynth-r31-RC2.exe <- try this build and see if it still happens

**Comment by VFR-maniac** [comment]
> What's your cpu? I think it could depend on how many threads are used.

i5 3570K

> https://dl.dropboxusercontent.com/u/73468194/vapoursynth-r31-RC2.exe <- try this build and see if it still happens

still happens!

**Comment by myrsloik** [comment]
Odd, but does it happen when you use vspipe too?

**Comment by myrsloik** [comment]
I can't reproduce it and dubhater can't reproduce it either. There has to be some additional step required to make it happen.

**Comment by dubhater** [comment]
> Hmmm...
I apply your patches but I notice that I get jerkiness when I preview video frames on VirtualDub. Myrsloik, it seems nfMakeLinear makes duplicated calling of frame getter within consecutive frame requests. This request behavior brings about unnecessary decodings from random access points since requested frame numbers are back and forth. L-SMASH Works plugins does not assume such behavior. I'll revert this change unless you have a solution.

Is this still happening with VapourSynth R32? It turned out there was a bug.

**Comment by VFR-maniac** [comment]
No, no duplicated calls happen anymore. Thanks!

**Pull request closed without merging**
